# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Neris/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12364-DESKTOP-GB20E3M/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Neris/finalproject/finalproject.cache/wt [current_project]
set_property parent.project_path C:/Users/Neris/finalproject/finalproject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Neris/finalproject/finalproject.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/imports/Neris/myca_2/myca_2.srcs/sources_1/imports/adder/1bit_Adder.vhd
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/imports/Neris/soda/soda.srcs/sources_1/imports/experimento6/74LS169.vhd
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/imports/Neris/myca_2/myca_2.srcs/sources_1/imports/Neris/pilha/pilha.srcs/sources_1/imports/experimento5/pergunta1/74LS194.vhd
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/imports/Neris/myca_2/myca_2.srcs/sources_1/imports/Neris/contadorUP_DOWN/contadorUP_DOWN.srcs/sources_1/imports/pergunta3/updown.vhd
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/imports/Neris/myca_2/myca_2.srcs/sources_1/imports/adder/nbit_adder.vhd
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/imports/Neris/myca_2/myca_2.srcs/sources_1/new/opcode_decoder.vhd
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/imports/Neris/myca_2/myca_2.srcs/sources_1/new/Myca_2.vhd
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/imports/Neris/myca_2/myca_2.srcs/sources_1/new/ROM.vhd
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/imports/Neris/soda/soda.srcs/sources_1/imports/experimento6/comparador1bits.vhd
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/imports/Neris/soda/soda.srcs/sources_1/imports/experimento6/comparador4bits.vhd
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/imports/Neris/soda/soda.srcs/sources_1/imports/experimento6/deco_moeda.vhd
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/imports/Neris/soda/soda.srcs/sources_1/imports/experimento6/decode7segmento.vhd
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/imports/Neris/myca_2/myca_2.srcs/sources_1/new/mux3_8.vhd
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/imports/Neris/soda/soda.srcs/sources_1/imports/experimento6/somador.vhd
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/new/topmodule.vhd
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/new/somador4.vhd
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/imports/Documents/shifter_74LS174.vhd
  C:/Users/Neris/finalproject/finalproject.srcs/sources_1/imports/Documents/stack_nbit.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Neris/finalproject/finalproject.srcs/constrs_1/imports/experimento6/pins.xdc
set_property used_in_implementation false [get_files C:/Users/Neris/finalproject/finalproject.srcs/constrs_1/imports/experimento6/pins.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_module -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
